spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

 # profiles: dev

  datasource:
    name: video
    url: jdbc:mysql://localhost:3306/spzy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  typeAliasesPackage: cn.org.cflac.entity
    
    
    

