spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

     

  datasource:
    name: video
    url: jdbc:mysql://10.1.100.165:3306/spzy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: lar
    password: larlar
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled:  true
        

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  typeAliasesPackage: cn.org.cflac.entity

  
pic_upload_path: http://10.1.100.152:9000/resource
upload_path: /opt/lar/files/videomanager/videoresource
download_zip_path: /opt/lar/files/videomanager/videoresource/tempzip
temp_path: /opt/lar/files/videomanager