spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

 # profiles: dev

  datasource:
    name: video
    url: jdbc:mysql://10.1.100.165:3306/spzy
    username: lar
    password: larlar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL  
    show-sql : true
    hibernate:
      ddl-auto: update
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect
    
