spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

 # profiles: dev

  datasource:
    name: video
    url: jdbc:mysql://localhost:3306/spzy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled:  true
        

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  typeAliasesPackage: cn.org.cflac.entity
    
    
    

